### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by vmikk** [olehprylutskyi/spectralR#8]
- [ ] Vignette auto building
- [ ] Add spell check test (e.g., with `spelling::spell_check_test`)
- [ ] Deprecate `reshape2::melt`
- [x] Add unit testing (e.g., with [tinytest](https://github.com/markvanderloo/tinytest) or [testthat](https://testthat.r-lib.org/))
- [x] Test code coverage (e.g., with [Codecov](https://about.codecov.io/))
- [x] Continuous integration testing (`R-CMD-check`)

**Comment by cauricht** [comment]
Hi - nice app. 
Suggestions - 
1. Produce a meta report on which image dates were actually used in the processing and parameters e.g. cloud cover and pixel resolution, start and end dates i.e. the parameters used in get.pixel.data plus the actual image dates returned
2. Enable processing of a single image date, in addition to the current method of determining a median value for each pixel based on more than one image
Kind regards, chris@auricht.com
